azure_name = "testserver1"
azure_location = "East US"
private_ip_address_allocation = "Dynamic"
vm_size = "Standard_B1s"
create_option = "FromImage"
address_space =  "10.0.0.0/16"
address_prefixes = "10.0.1.0/24"